### ISSUE TITLE
pool_transactions_sandbox missing

### ISSUE THREAD

**Issue by AxelNennker** [hyperledger/indy-client#226]
Hi,

I am following the getting-started guide which at some point wants me to run 'connect test'.
This gives me the following error message.

ALICE> connect test

The information required to connect this client to the nodes cannot be found. 
This is an error. To correct the error, get the file containing genesis transactions 
(the file name is `pool_transactions_sandbox`) from the github repository and place 
it in directory `/home/ignisvulpis/.sovrin`.

The github url is https://github.com/sovrin-foundation/sovrin-client/tree/stable/data.

ALICE> 

Problem is that this file does not seem to exist.

Sovrin client version is 0.3.15 on Ubuntu

How do I fix this?

Axel

**Comment by dhh1128** [comment]
Axel: These files got moved to sovrin-common. Same URL except that sovrin-client becomes sovrin-common.

**Comment by dhh1128** [comment]
@glowkey Is this the bug that you fixed last week?

**Comment by glowkey** [comment]
No.  INDY-212 dealt with pool_transactions_live and transactions_live but not pool_transactions_sandbox.

**Comment by dhh1128** [comment]
@AxelNennker It seems like you may have a damaged network, given your other issue about problems with vagrant. If you are running against the true global network, and not against a local network of nodes hosted via vagrant, then you will find that "connect live" will work better, over the next several weeks, than "connect test". This is because the live network is being updated and maintained more aggressively. (For the time being, it does not hurt to do a test on the live network, but that will change in a month or so as identities become permanent.) However, neither the test sandbox nor the live sandbox have Faber, Thrift, and Acme agents running at the moment, which means the workflows of the Getting Started Guide will only work through the vagrant-based variant that depends only on a local network.
